-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("T'zane", {
	[261552] = "red",
	[261600] = "yellow",
	[261605] = {"blue","orange"},
	[262004] = {"blue","purple"},
})

BigWigs:AddSounds("T'zane", {
	[261552] = "long",
	[261600] = "info",
	[261605] = "alarm",
	[262004] = "warning",
})

BigWigs:AddColors("Ji'arak", {
	[260908] = "yellow",
	[261088] = "red",
	[261467] = "orange",
})

BigWigs:AddSounds("Ji'arak", {
	[260908] = "info",
	[261088] = "long",
	[261467] = "alert",
})

BigWigs:AddColors("Hailstone Construct", {
	[274891] = "yellow",
	[274895] = "red",
})

BigWigs:AddSounds("Hailstone Construct", {
	[274891] = "long",
	[274895] = "warning",
})

BigWigs:AddColors("Azurethos, The Winged Typhoon", {
	[274829] = "red",
	[274832] = "purple",
	[274839] = "yellow",
})

BigWigs:AddSounds("Azurethos, The Winged Typhoon", {
	[274829] = "warning",
	[274832] = "long",
	[274839] = "long",
})

BigWigs:AddColors("Doom's Howl", {
	[271120] = "blue",
	[271163] = "purple",
	[271164] = "orange",
	[271223] = "cyan",
	[271800] = "red",
})

BigWigs:AddSounds("Doom's Howl", {
	[271120] = "alarm",
	[271163] = "alert",
	[271164] = "info",
	[271223] = "long",
	[271800] = "warning",
})

BigWigs:AddColors("The Lion's Roar", {
	[271120] = "blue",
	[271163] = "purple",
	[271164] = "orange",
	[271223] = "cyan",
	[271800] = "red",
})

BigWigs:AddSounds("The Lion's Roar", {
	[271120] = "alarm",
	[271163] = "alert",
	[271164] = "info",
	[271223] = "long",
	[271800] = "warning",
})

BigWigs:AddColors("Warbringer Yenajz", {
	[274842] = "yellow",
	[274904] = "blue",
	[274932] = "red",
})

BigWigs:AddSounds("Warbringer Yenajz", {
	[274842] = "info",
	[274904] = "alarm",
	[274932] = "long",
})

BigWigs:AddColors("Dunegorger Kraulok", {
	[275200] = "orange",
	[276046] = "red",
})

BigWigs:AddSounds("Dunegorger Kraulok", {
	[275200] = "info",
	[276046] = "long",
})

BigWigs:AddColors("Champion of the Light Alliance", {
	[282113] = "cyan",
	[283573] = {"blue","purple"},
	[283582] = "blue",
	[283598] = "yellow",
	[283628] = "yellow",
	[283650] = "orange",
	[283662] = "cyan",
	[283933] = "red",
	[284436] = "cyan",
	[284469] = "cyan",
	[284474] = "red",
	[284595] = "yellow",
	[287469] = "red",
})

BigWigs:AddSounds("Champion of the Light Alliance", {
	[282113] = "info",
	[283573] = "alarm",
	[283582] = "alarm",
	[283598] = "alert",
	[283628] = "alert",
	[283650] = "warning",
	[283662] = "long",
	[283933] = "warning",
	[284436] = "info",
	[284469] = "info",
	[284474] = "warning",
	[284595] = "alarm",
	[287469] = "warning",
})

BigWigs:AddColors("Champion of the Light Horde", {
	[282113] = "cyan",
	[283573] = {"blue","purple"},
	[283582] = "blue",
	[283598] = "yellow",
	[283628] = "yellow",
	[283650] = "orange",
	[283662] = "cyan",
	[283933] = "red",
	[284436] = "cyan",
	[284469] = "cyan",
	[284474] = "red",
	[284595] = "yellow",
	[287469] = "red",
})

BigWigs:AddSounds("Champion of the Light Horde", {
	[282113] = "info",
	[283573] = "alarm",
	[283582] = "alarm",
	[283598] = "alert",
	[283628] = "alert",
	[283650] = "warning",
	[283662] = "long",
	[283933] = "warning",
	[284436] = "info",
	[284469] = "info",
	[284474] = "warning",
	[284595] = "alarm",
	[287469] = "warning",
})

BigWigs:AddColors("Jadefire Masters Alliance", {
	[282030] = "red",
	[282037] = {"blue","purple"},
	[282040] = "yellow",
	[284374] = "red",
	[284656] = {"green","yellow"},
	[285428] = "yellow",
	[285632] = "blue",
	[285645] = "yellow",
	[286379] = {"green","orange"},
	[286396] = "orange",
	[286425] = "cyan",
	[286436] = "yellow",
	[286988] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Jadefire Masters Alliance", {
	[282030] = "warning",
	[282037] = {"alarm","warning"},
	[282040] = "long",
	[284374] = "warning",
	[284656] = "long",
	[285428] = "long",
	[285632] = "alarm",
	[285645] = "info",
	[286379] = "warning",
	[286396] = "alert",
	[286425] = "info",
	[286436] = "alert",
	[286988] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Grong Horde", {
	[281936] = "orange",
	[282179] = "yellow",
	[282215] = {"blue","red"},
	[282243] = "yellow",
	[282247] = "yellow",
	[283069] = "blue",
	[285659] = {"blue","green"},
	[285660] = "green",
	[285671] = {"blue","purple"},
	[285875] = {"blue","purple"},
	[285994] = "red",
	[289401] = {"blue","purple"},
})

BigWigs:AddSounds("Grong Horde", {
	[281936] = "alarm",
	[282179] = "alert",
	[282215] = {"alarm","warning"},
	[282243] = "alert",
	[282247] = "long",
	[283069] = "alarm",
	[285660] = "info",
	[285671] = "alarm",
	[285875] = "alert",
	[285994] = "warning",
	[289401] = "alarm",
})

BigWigs:AddColors("Grong Alliance", {
	[282399] = "orange",
	[282471] = {"blue","red"},
	[282526] = "yellow",
	[282533] = "yellow",
	[282543] = "yellow",
	[285671] = {"blue","purple"},
	[285875] = {"blue","purple"},
	[285994] = "red",
	[286373] = "blue",
	[286434] = {"blue","green"},
	[286435] = "green",
	[289401] = {"blue","purple"},
})

BigWigs:AddSounds("Grong Alliance", {
	[282399] = "alarm",
	[282471] = {"alarm","warning"},
	[282526] = "long",
	[282533] = "alert",
	[282543] = "alert",
	[285671] = "alarm",
	[285875] = "alert",
	[285994] = "warning",
	[286373] = "alarm",
	[286435] = "info",
	[289401] = "alarm",
})

BigWigs:AddColors("Jadefire Masters Horde", {
	[282030] = "red",
	[282037] = {"blue","purple"},
	[282040] = "yellow",
	[284374] = "red",
	[284656] = {"green","yellow"},
	[285428] = "yellow",
	[285632] = "blue",
	[285645] = "yellow",
	[286379] = {"green","orange"},
	[286396] = "orange",
	[286425] = "cyan",
	[286436] = "yellow",
	[286988] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Jadefire Masters Horde", {
	[282030] = "warning",
	[282037] = {"alarm","warning"},
	[282040] = "long",
	[284374] = "warning",
	[284656] = "long",
	[285428] = "long",
	[285632] = "alarm",
	[285645] = "info",
	[286379] = "warning",
	[286396] = "alert",
	[286425] = "info",
	[286436] = "alert",
	[286988] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Opulence", {
	[-19494] = "blue",
	[282939] = "red",
	[283507] = {"blue","yellow"},
	[283606] = "yellow",
	[284424] = "blue",
	[284470] = {"blue","green","orange"},
	[284493] = "orange",
	[284519] = {"blue","green"},
	[284645] = {"blue","green"},
	[284941] = "red",
	[285014] = {"blue","yellow"},
	[285479] = "blue",
	[285995] = "yellow",
	[286026] = "orange",
	[286541] = "cyan",
	[287037] = "purple",
	[287070] = "cyan",
	[287072] = {"blue","yellow"},
	[287074] = "blue",
	[289155] = "orange",
	[289383] = "blue",
})

BigWigs:AddSounds("Opulence", {
	[-19494] = "long",
	[282939] = "alarm",
	[283507] = "warning",
	[283606] = "alert",
	[284424] = "alarm",
	[284470] = "alarm",
	[284493] = "alert",
	[284519] = "info",
	[284941] = "warning",
	[285014] = "alert",
	[285479] = "alarm",
	[285995] = "long",
	[286026] = "alarm",
	[286541] = "long",
	[287037] = "alarm",
	[287070] = "info",
	[287072] = "warning",
	[287074] = "alarm",
	[289155] = "info",
	[289383] = "info",
})

BigWigs:AddColors("Conclave of the Chosen", {
	[282079] = "orange",
	[282098] = "yellow",
	[282107] = "red",
	[282135] = {"blue","green","orange"},
	[282155] = "cyan",
	[282209] = "blue",
	[282411] = "red",
	[282444] = {"blue","purple"},
	[282447] = {"blue","yellow"},
	[285879] = {"blue","green","yellow"},
	[285893] = "yellow",
	[285945] = {"blue","purple"},
	[286811] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Conclave of the Chosen", {
	[282079] = "alarm",
	[282098] = "alert",
	[282107] = "warning",
	[282135] = {"alarm","info","warning"},
	[282155] = "info",
	[282209] = "warning",
	[282411] = "alarm",
	[282444] = "alarm",
	[282447] = "warning",
	[285879] = {"alert","info"},
	[285893] = "alert",
	[285945] = "alarm",
	[286811] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("King Rastakhan", {
	[284686] = {"blue","green","orange"},
	[284719] = "cyan",
	[284781] = {"blue","yellow"},
	[284831] = {"blue","purple"},
	[284933] = "yellow",
	[285003] = "cyan",
	[285172] = "cyan",
	[285195] = "blue",
	[285213] = "purple",
	[285346] = {"blue","orange"},
	[286742] = "red",
	[287333] = "orange",
	[288449] = {"blue","orange"},
	[290450] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("King Rastakhan", {
	[284686] = "alarm",
	[284719] = "info",
	[284781] = "warning",
	[284831] = "warning",
	[284933] = "alert",
	[285003] = "info",
	[285172] = "info",
	[285195] = "alarm",
	[285213] = "alarm",
	[285346] = {"alarm","warning"},
	[286742] = "alarm",
	[287333] = "warning",
	[288449] = "warning",
	[290450] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("High Tinker Mekkatorque", {
	[282153] = "yellow",
	[282205] = "orange",
	[284168] = "blue",
	[286646] = {"blue","yellow"},
	[286693] = "yellow",
	[287929] = "yellow",
	[287952] = "red",
	[288410] = "cyan",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("High Tinker Mekkatorque", {
	[282153] = "warning",
	[282205] = "alarm",
	[284168] = "alert",
	[286646] = "warning",
	[286693] = "long",
	[287929] = "long",
	[287952] = "alert",
	[288410] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Stormwall Blockade", {
	[284262] = "orange",
	[284362] = {"blue","yellow"},
	[284383] = "cyan",
	[284405] = {"blue","red"},
	[285000] = {"blue","purple"},
	[285017] = "red",
	[285118] = "orange",
	[285350] = {"blue","yellow"},
	[286558] = "red",
	[287995] = "red",
	[288205] = {"blue","yellow"},
	[288696] = {"green","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Stormwall Blockade", {
	[284262] = "alarm",
	[284362] = "alert",
	[284383] = {"alarm","info"},
	[284405] = "warning",
	[285000] = {"alarm","warning"},
	[285017] = "warning",
	[285118] = "alert",
	[285350] = "warning",
	[286558] = "info",
	[287995] = "info",
	[288205] = "warning",
	[288696] = {"info","long"},
	["stages"] = "long",
})

BigWigs:AddColors("Lady Jaina Proudmoore", {
	[-19825] = "cyan",
	[-19690] = "yellow",
	[285177] = "red",
	[285253] = {"blue","purple"},
	[285254] = {"blue","yellow"},
	[285459] = "orange",
	[285725] = "red",
	[287365] = "blue",
	[287490] = {"blue","yellow"},
	[287626] = {"blue","yellow"},
	[287925] = "cyan",
	[287993] = {"blue","green"},
	[288038] = "blue",
	[288169] = "red",
	[288212] = {"blue","yellow"},
	[288221] = "green",
	[288297] = "blue",
	[288345] = "red",
	[288374] = {"blue","yellow"},
	[288441] = "orange",
	[288619] = "yellow",
	[288747] = "cyan",
	[289219] = "red",
	[289220] = {"blue","yellow"},
	[289387] = "blue",
	[289488] = "yellow",
	[289940] = "yellow",
	[290084] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Lady Jaina Proudmoore", {
	[-19825] = {"info","long"},
	[-19690] = "info",
	[285177] = "alarm",
	[285253] = {"alarm","alert"},
	[285254] = "warning",
	[285459] = "long",
	[285725] = "warning",
	[287365] = "alarm",
	[287490] = "warning",
	[287626] = "alert",
	[287925] = "info",
	[287993] = {"alarm","info"},
	[288038] = "alarm",
	[288169] = "long",
	[288212] = "warning",
	[288221] = "info",
	[288297] = "alarm",
	[288345] = "alarm",
	[288374] = "alert",
	[288441] = "long",
	[288619] = "alert",
	[288747] = "long",
	[289219] = "alarm",
	[289220] = "alert",
	[289387] = "alarm",
	[289488] = "alert",
	[289940] = "alert",
	[290084] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Battle of Dazar'alor Trash", {
	[288808] = "blue",
	[288815] = "red",
	[288959] = {"blue","yellow"},
	[289772] = {"blue","red"},
	[289917] = {"blue","orange"},
	[289937] = "yellow",
	[290578] = {"blue","red"},
})

BigWigs:AddSounds("Battle of Dazar'alor Trash", {
	[288808] = "alarm",
	[288815] = "long",
	[288959] = "warning",
	[289772] = "long",
	[289917] = "warning",
	[289937] = "long",
	[290578] = "warning",
})

BigWigs:AddColors("The Restless Cabal", {
	[282384] = {"blue","purple"},
	[282386] = {"blue","purple"},
	[282407] = "yellow",
	[282432] = {"blue","yellow"},
	[282517] = "red",
	[282540] = {"blue","yellow"},
	[282561] = {"blue","yellow"},
	[282566] = {"blue","green"},
	[282589] = "red",
	[282675] = "red",
	[282741] = {"blue","cyan","orange"},
	[282742] = "orange",
	[282886] = {"cyan","orange"},
	[282914] = {"blue","red"},
	[287876] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Restless Cabal", {
	[282384] = "alert",
	[282386] = "alarm",
	[282407] = "alert",
	[282432] = "alert",
	[282517] = "long",
	[282540] = "warning",
	[282561] = "alert",
	[282566] = {"info","warning"},
	[282589] = "warning",
	[282675] = "alert",
	[282741] = {"alarm","info"},
	[282742] = "alarm",
	[282886] = {"alarm","info"},
	[282914] = "warning",
	[287876] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Uu'nat, Harbinger of the Void", {
	[284583] = {"blue","cyan"},
	[284722] = {"blue","cyan"},
	[284804] = {"blue","green"},
	[284809] = "cyan",
	[284851] = {"blue","purple"},
	[285185] = "orange",
	[285307] = "purple",
	[285345] = "orange",
	[285376] = "yellow",
	[285416] = "yellow",
	[285427] = "yellow",
	[285453] = "orange",
	[285562] = "yellow",
	[285638] = "orange",
	[285652] = {"blue","yellow"},
	[285685] = "orange",
	[285820] = "cyan",
	[293653] = {"blue","green","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Uu'nat, Harbinger of the Void", {
	[284583] = "long",
	[284722] = "info",
	[284804] = "info",
	[284809] = {"info","long"},
	[284851] = "alarm",
	[285185] = "alarm",
	[285307] = "alert",
	[285345] = "alarm",
	[285376] = "long",
	[285416] = "alert",
	[285427] = {"alert","long"},
	[285453] = "warning",
	[285562] = "alarm",
	[285638] = "warning",
	[285652] = "warning",
	[285685] = "warning",
	[285820] = "info",
	[293653] = {"alarm","info","warning"},
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Abyssal Commander Sivara", {
	[-20300] = {"blue","green","purple"},
	[-20006] = {"blue","yellow"},
	[294726] = "blue",
	[295332] = "purple",
	[295601] = {"blue","orange"},
	[295791] = {"blue","orange"},
	[296551] = "red",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Abyssal Commander Sivara", {
	[-20300] = "info",
	[-20006] = "alarm",
	[294726] = "alarm",
	[295332] = "alert",
	[295601] = "alarm",
	[295791] = "long",
	[296551] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Radiance of Azshara", {
	[295916] = "cyan",
	[296428] = "yellow",
	[296459] = "yellow",
	[296566] = {"blue","purple"},
	[296701] = "orange",
	[296737] = {"blue","green","yellow"},
	[296894] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Radiance of Azshara", {
	[295916] = "long",
	[296428] = "alarm",
	[296459] = "long",
	[296566] = {"alarm","alert"},
	[296701] = "warning",
	[296737] = "alert",
	[296894] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Blackwater Behemoth", {
	[292083] = "cyan",
	[292127] = "blue",
	[292133] = "green",
	[292138] = "green",
	[292159] = {"blue","yellow"},
	[292205] = "green",
	[292270] = "orange",
	[292307] = "blue",
	[298428] = {"blue","purple"},
	[301180] = "blue",
	[301494] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Blackwater Behemoth", {
	[292083] = "long",
	[292127] = "alarm",
	[292133] = "long",
	[292138] = "info",
	[292159] = {"alarm","alert"},
	[292205] = "info",
	[292270] = "alarm",
	[292307] = "warning",
	[298428] = "alert",
	[301180] = "info",
	[301494] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Lady Ashvane", {
	[-20096] = {"blue","yellow"},
	[296662] = "cyan",
	[296725] = {"blue","purple"},
	[296752] = "blue",
	[297397] = {"blue","red"},
	[298056] = "orange",
	["stages"] = "orange",
})

BigWigs:AddSounds("Lady Ashvane", {
	[-20096] = {"alert","warning"},
	[296662] = "long",
	[296725] = "alert",
	[296752] = "alarm",
	[297397] = "warning",
	[298056] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Orgozoa", {
	[295779] = {"blue","yellow"},
	[295822] = "red",
	[296691] = "orange",
	[298103] = "orange",
	[298156] = {"blue","purple"},
	[298242] = "yellow",
	[298465] = "cyan",
	[298548] = "cyan",
	[305048] = {"blue","red"},
	[305057] = "cyan",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Orgozoa", {
	[295779] = "alert",
	[295822] = "alarm",
	[296691] = "warning",
	[298103] = "long",
	[298156] = {"alarm","warning"},
	[298242] = "alert",
	[298465] = "info",
	[298548] = "long",
	[305048] = "warning",
	[305057] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("The Queen's Court", {
	[296716] = "red",
	[296851] = {"blue","yellow"},
	[297325] = "red",
	[297566] = "cyan",
	[297585] = {"blue","cyan"},
	[297656] = {"blue","cyan"},
	[298050] = {"cyan","yellow"},
	[299914] = {"blue","yellow"},
	[300088] = "cyan",
	[300545] = "blue",
	[301244] = "cyan",
	[301807] = "red",
	[301830] = {"blue","purple"},
	[301947] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Queen's Court", {
	[296716] = "alert",
	[296851] = "alert",
	[297325] = "warning",
	[297566] = "info",
	[297585] = {"alarm","info"},
	[297656] = {"alarm","info"},
	[298050] = {"alert","info"},
	[299914] = "warning",
	[300088] = "long",
	[300545] = "alarm",
	[301244] = "info",
	[301807] = "warning",
	[301830] = "alarm",
	[301947] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Za'qul, Herald of Ny'alotha", {
	[292963] = {"blue","yellow"},
	[292971] = "blue",
	[292996] = "cyan",
	[293509] = {"blue","yellow"},
	[294535] = "yellow",
	[295099] = {"blue","green"},
	[295444] = "blue",
	[295814] = "red",
	[296018] = {"blue","yellow"},
	[298192] = "blue",
	[299702] = "yellow",
	[301141] = "orange",
	[303971] = "red",
	[304733] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Za'qul, Herald of Ny'alotha", {
	[292963] = "alert",
	[292971] = "alarm",
	[292996] = "info",
	[293509] = "alert",
	[294535] = "alert",
	[295099] = "long",
	[295444] = "alert",
	[295814] = "warning",
	[296018] = "alert",
	[298192] = "alarm",
	[299702] = "alert",
	[301141] = "warning",
	[303971] = "warning",
	[304733] = "long",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Queen Azshara", {
	[-20480] = "cyan",
	[-20410] = "yellow",
	[-20408] = "yellow",
	[-20355] = "yellow",
	[297371] = "cyan",
	[297372] = "cyan",
	[297907] = "blue",
	[297912] = "red",
	[297934] = "orange",
	[297937] = "orange",
	[297972] = "orange",
	[298014] = {"blue","purple"},
	[298021] = "purple",
	[298121] = "cyan",
	[298531] = "orange",
	[298569] = "blue",
	[298756] = {"blue","purple"},
	[298787] = "yellow",
	[299094] = {"blue","yellow"},
	[299250] = {"blue","cyan"},
	[300074] = "orange",
	[300428] = "cyan",
	[300478] = "orange",
	[300492] = {"blue","yellow"},
	[300519] = "red",
	[300620] = {"blue","yellow"},
	[300743] = {"blue","purple"},
	[300768] = "orange",
	[300866] = {"blue","yellow"},
	[300877] = {"blue","cyan"},
	[301078] = {"blue","yellow"},
	[301431] = "red",
	[302999] = "blue",
	[303657] = {"blue","yellow"},
	[303986] = {"blue","yellow"},
	[304475] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Queen Azshara", {
	[-20480] = {"info","long"},
	[-20410] = "long",
	[-20408] = "long",
	[-20355] = "long",
	[297371] = "long",
	[297372] = "long",
	[297907] = "alarm",
	[297912] = "alarm",
	[297934] = "long",
	[297937] = "long",
	[297972] = "alert",
	[298014] = {"alert","warning"},
	[298021] = "warning",
	[298121] = "info",
	[298531] = "alarm",
	[298569] = {"alarm","warning"},
	[298756] = "alert",
	[298787] = "alert",
	[299094] = "alarm",
	[299250] = {"alarm","long"},
	[300074] = "alarm",
	[300428] = "info",
	[300478] = "warning",
	[300492] = "alert",
	[300519] = "warning",
	[300620] = "long",
	[300743] = {"alert","warning"},
	[300768] = "long",
	[300866] = "alert",
	[300877] = "alarm",
	[301078] = "alert",
	[301431] = "warning",
	[302999] = "alarm",
	[303657] = "warning",
	[303986] = {"alarm","alert"},
	[304475] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Wrathion", {
	[305978] = {"blue","purple","yellow"},
	[306163] = {"blue","yellow"},
	[306289] = "red",
	[306735] = "red",
	[307013] = "red",
	[313250] = {"blue","green"},
	[313255] = {"blue","green"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Wrathion", {
	[305978] = {"alert","warning"},
	[306163] = "warning",
	[306289] = "alarm",
	[306735] = "alert",
	[307013] = "warning",
	[313250] = "info",
	[313255] = {"info","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Maut", {
	[305663] = "orange",
	[305722] = "cyan",
	[307586] = {"blue","green"},
	[307806] = "blue",
	[308044] = "red",
	[308872] = "purple",
	[308903] = "yellow",
	[310129] = {"blue","purple"},
	[314337] = {"green","red"},
	[314993] = "blue",
})

BigWigs:AddSounds("Maut", {
	[305663] = "alert",
	[305722] = "long",
	[307586] = "warning",
	[307806] = "warning",
	[308044] = "long",
	[308872] = "alarm",
	[308903] = "alarm",
	[310129] = "alarm",
	[314337] = {"info","warning"},
	[314993] = "warning",
})

BigWigs:AddColors("The Prophet Skitra", {
	[307725] = {"blue","green"},
	[307950] = {"blue","orange"},
	[308059] = {"blue","purple"},
	[313239] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("The Prophet Skitra", {
	[307725] = "long",
	[307950] = "warning",
	[308059] = {"alarm","warning"},
	[313239] = "alert",
})

BigWigs:AddColors("Dark Inquisitor Xanesh", {
	[305575] = "blue",
	[306208] = "yellow",
	[306319] = {"blue","yellow"},
	[311551] = {"blue","purple"},
	[312336] = "red",
	[312406] = {"blue","cyan"},
	[313264] = {"blue","red"},
})

BigWigs:AddSounds("Dark Inquisitor Xanesh", {
	[305575] = "alarm",
	[306208] = "long",
	[306319] = {"alarm","alert"},
	[311551] = {"alarm","alert"},
	[312336] = "warning",
	[312406] = "alarm",
	[313264] = "warning",
})

BigWigs:AddColors("The Hivemind", {
	[307201] = "orange",
	[307213] = "orange",
	[307232] = "orange",
	[307569] = "red",
	[307637] = "yellow",
	[307968] = "yellow",
	[310340] = "orange",
	[313652] = "yellow",
	[313672] = "blue",
	[314583] = "red",
})

BigWigs:AddSounds("The Hivemind", {
	[307201] = "long",
	[307213] = "long",
	[307232] = "warning",
	[307569] = "info",
	[307637] = "alert",
	[307968] = "alert",
	[310340] = "info",
	[313652] = "long",
	[313672] = "alarm",
	[314583] = "warning",
})

BigWigs:AddColors("Shad'har the Insatiable", {
	[306448] = "orange",
	[306928] = "red",
	[306929] = "red",
	[306930] = "red",
	[306942] = "cyan",
	[306953] = {"blue","yellow"},
	[307471] = {"blue","cyan","purple"},
	[307472] = {"blue","cyan","purple"},
	[312099] = {"blue","green"},
	[312328] = "orange",
	[314736] = "blue",
	[318078] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shad'har the Insatiable", {
	[306448] = "alarm",
	[306928] = "alert",
	[306929] = "alert",
	[306930] = "alert",
	[306942] = "info",
	[306953] = "info",
	[307471] = {"alarm","info"},
	[307472] = {"alarm","info"},
	[312099] = {"info","long"},
	[312328] = "alarm",
	[314736] = "alarm",
	[318078] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Drest'agath", {
	[308377] = "green",
	[308941] = {"cyan","orange"},
	[310246] = "red",
	[310277] = {"blue","purple"},
	[310329] = "yellow",
	[310358] = {"blue","yellow"},
	[310390] = "orange",
	[310580] = "blue",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Drest'agath", {
	[308377] = "warning",
	[308941] = {"info","long"},
	[310246] = "alarm",
	[310277] = "alarm",
	[310329] = "alert",
	[310358] = "warning",
	[310390] = "alert",
	[310580] = "alarm",
	["adds"] = "info",
})

BigWigs:AddColors("Vexiona", {
	[307020] = "orange",
	[307057] = "cyan",
	[307116] = "cyan",
	[307314] = {"blue","yellow"},
	[307343] = "blue",
	[307359] = {"blue","red"},
	[307403] = "yellow",
	[307639] = "red",
	[307729] = "orange",
	[310323] = {"blue","yellow"},
	[315762] = "red",
	[315932] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Vexiona", {
	[307020] = "alarm",
	[307057] = "info",
	[307116] = "info",
	[307314] = "warning",
	[307343] = "alarm",
	[307359] = "warning",
	[307403] = "alert",
	[307639] = "alert",
	[307729] = "long",
	[310323] = "warning",
	[315762] = "warning",
	[315932] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Ra-den the Despoiled", {
	[306273] = {"blue","cyan"},
	[306603] = "orange",
	[306732] = "cyan",
	[306733] = "cyan",
	[306819] = {"blue","purple"},
	[306865] = "yellow",
	[306866] = "yellow",
	[306881] = {"blue","red"},
	[310003] = "yellow",
	[310019] = {"blue","cyan","green"},
	[312996] = "cyan",
	[313077] = {"blue","red"},
	[313213] = {"blue","purple","red"},
	[314484] = "yellow",
	[315252] = "blue",
	[316065] = {"blue","cyan"},
	["essences"] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ra-den the Despoiled", {
	[306273] = "warning",
	[306603] = "alarm",
	[306732] = "info",
	[306733] = "info",
	[306819] = "alarm",
	[306865] = "alert",
	[306866] = "alert",
	[306881] = "alarm",
	[310003] = "alert",
	[310019] = {"info","warning"},
	[312996] = "info",
	[313077] = "warning",
	[313213] = {"alarm","alert"},
	[314484] = "alert",
	[315252] = "alarm",
	[316065] = "warning",
	["essences"] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Il'gynoth, Corruption Reborn", {
	[309961] = "purple",
	[310322] = "blue",
	[310433] = "orange",
	[311401] = "yellow",
	[313759] = {"blue","yellow"},
	[318383] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Il'gynoth, Corruption Reborn", {
	[309961] = "warning",
	[310322] = "alarm",
	[310433] = "long",
	[311401] = "long",
	[313759] = "warning",
	[318383] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Carapace of N'Zoth", {
	[-21069] = "red",
	[-20565] = "red",
	[-20560] = "red",
	[306973] = {"blue","yellow"},
	[306984] = "yellow",
	[306988] = "orange",
	[307011] = "blue",
	[307064] = "green",
	[307079] = {"blue","green"},
	[307092] = "red",
	[307809] = "yellow",
	[313039] = "red",
	[315947] = "orange",
	[315954] = {"blue","purple"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Carapace of N'Zoth", {
	[-21069] = "alert",
	[-20565] = "alert",
	[-20560] = "info",
	[306973] = "warning",
	[306984] = "warning",
	[306988] = "alarm",
	[307011] = "info",
	[307064] = "long",
	[307092] = "alarm",
	[307809] = "alert",
	[315954] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("N'Zoth, the Corruptor", {
	[-21491] = "yellow",
	[-21286] = "yellow",
	[309698] = "purple",
	[309991] = "blue",
	[310042] = "red",
	[310184] = "yellow",
	[312155] = "green",
	[312866] = "orange",
	[313184] = {"blue","green"},
	[313400] = {"blue","orange","red"},
	[313609] = {"blue","yellow"},
	[313960] = "cyan",
	[315772] = "yellow",
	[315927] = {"blue","green","orange"},
	[316463] = "green",
	[316711] = {"blue","purple","red"},
	[316970] = "yellow",
	[317066] = "orange",
	[317102] = "red",
	[318091] = "cyan",
	[318196] = {"blue","orange"},
	[318449] = "yellow",
	[318459] = {"blue","orange"},
	[318971] = "orange",
	[318976] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("N'Zoth, the Corruptor", {
	[-21491] = "info",
	[-21286] = "long",
	[309698] = "alert",
	[309991] = "alarm",
	[310042] = "warning",
	[310184] = "alarm",
	[312155] = "long",
	[312866] = "warning",
	[313184] = "info",
	[313400] = {"alarm","alert"},
	[313609] = "warning",
	[313960] = "alert",
	[315772] = "long",
	[315927] = {"info","warning"},
	[316463] = "long",
	[316711] = {"alarm","warning"},
	[316970] = "alert",
	[317066] = "alarm",
	[317102] = "warning",
	[318091] = "long",
	[318196] = "warning",
	[318449] = "alert",
	[318459] = "warning",
	[318971] = "alarm",
	[318976] = "long",
	["berserk"] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Taloc", {
	[270290] = "blue",
	[271224] = {"blue","yellow"},
	[271296] = "red",
	[271728] = "orange",
	[271895] = {"blue","yellow"},
	[275189] = "yellow",
	[275205] = {"blue","orange"},
	[275270] = "blue",
	[275432] = {"blue","red"},
	["stages"] = "green",
})

BigWigs:AddSounds("Taloc", {
	[270290] = "alarm",
	[271224] = "warning",
	[271296] = "warning",
	[271728] = "alarm",
	[271895] = "alert",
	[275189] = "alert",
	[275205] = "warning",
	[275270] = "warning",
	[275432] = {"alarm","long"},
	["stages"] = "long",
})

BigWigs:AddColors("MOTHER", {
	[267787] = {"blue","purple","red"},
	[267795] = {"blue","yellow"},
	[267878] = "red",
	[268198] = "orange",
	[268253] = {"blue","yellow"},
	[269051] = {"cyan","red"},
	[274205] = {"blue","green"},
	[279662] = {"blue","yellow"},
})

BigWigs:AddSounds("MOTHER", {
	[267787] = {"alarm","alert"},
	[267795] = {"alarm","alert"},
	[267878] = "warning",
	[268198] = "alert",
	[268253] = {"alarm","alert"},
	[269051] = {"alarm","info"},
	[274205] = "long",
	[279662] = "warning",
})

BigWigs:AddColors("Fetid Devourer", {
	[262277] = "purple",
	[262288] = "orange",
	[262313] = {"blue","orange"},
	[262314] = {"blue","orange"},
	[262364] = {"cyan","red"},
	[262378] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["breath"] = "yellow",
})

BigWigs:AddSounds("Fetid Devourer", {
	[262277] = "alert",
	[262288] = "alarm",
	[262313] = {"info","warning"},
	[262314] = "warning",
	[262364] = {"long","warning"},
	[262378] = "info",
	["berserk"] = "alarm",
	["breath"] = "alert",
})

BigWigs:AddColors("Zek'voz, Herald of N'zoth", {
	[-18397] = "cyan",
	[-18390] = "cyan",
	[264382] = {"blue","yellow"},
	[265231] = "orange",
	[265248] = "purple",
	[265360] = {"blue","yellow"},
	[265530] = "red",
	[265646] = {"blue","red"},
	[265662] = "blue",
	[267180] = "yellow",
	[267239] = "yellow",
	["mythic_adds"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("Zek'voz, Herald of N'zoth", {
	[-18397] = "long",
	[-18390] = "long",
	[264382] = {"alert","warning"},
	[265231] = "alarm",
	[265248] = "alert",
	[265360] = "warning",
	[265530] = "long",
	[265646] = "warning",
	[265662] = "long",
	[267180] = "alert",
	[267239] = "alert",
	["mythic_adds"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Vectis", {
	[265127] = "blue",
	[265143] = "blue",
	[265178] = {"blue","purple"},
	[265206] = "orange",
	[265212] = {"blue","orange"},
	[265217] = "cyan",
	[266459] = "red",
	[267242] = "orange",
	[274990] = "blue",
})

BigWigs:AddSounds("Vectis", {
	[265127] = "warning",
	[265143] = "alarm",
	[265178] = "alert",
	[265206] = "alarm",
	[265212] = "alert",
	[265217] = {"info","long"},
	[266459] = "warning",
	[267242] = "alarm",
	[274990] = "warning",
})

BigWigs:AddColors("Zul", {
	[-18530] = "cyan",
	[269936] = "blue",
	[273288] = "yellow",
	[273350] = "orange",
	[273361] = "orange",
	[273365] = {"blue","yellow"},
	[273451] = "red",
	[274271] = {"blue","orange"},
	[274358] = {"blue","purple"},
	[276299] = "yellow",
	["bloodhexer"] = "cyan",
	["crawg"] = "cyan",
	["crusher"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("Zul", {
	[269936] = "warning",
	[273288] = "alert",
	[273350] = "alert",
	[273361] = "info",
	[273365] = "warning",
	[273451] = "alarm",
	[274271] = "alarm",
	[274358] = "warning",
	[276299] = "alarm",
	["bloodhexer"] = "long",
	["crawg"] = "long",
	["crusher"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Mythrax the Unraveler", {
	[272115] = "orange",
	[272404] = "red",
	[272536] = {"blue","yellow"},
	[273282] = {"blue","purple","red"},
	[273538] = "orange",
	[273810] = "yellow",
	[273949] = "red",
	[274230] = "green",
	[276922] = {"cyan","green","orange"},
	[279013] = "red",
	[279157] = "orange",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Mythrax the Unraveler", {
	[272115] = "long",
	[272404] = "warning",
	[272536] = "alert",
	[273282] = {"alarm","alert"},
	[273538] = "alert",
	[273810] = "long",
	[273949] = "warning",
	[274230] = "info",
	[276922] = {"info","long"},
	[279013] = "long",
	[279157] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("G'huun", {
	[-18109] = "green",
	[263235] = {"blue","red"},
	[263307] = "orange",
	[263321] = "blue",
	[263482] = "green",
	[267409] = "red",
	[267412] = "purple",
	[267427] = "yellow",
	[267462] = "orange",
	[267509] = "cyan",
	[270287] = "blue",
	[270373] = "yellow",
	[270447] = {"blue","purple"},
	[272506] = {"blue","orange"},
	[274582] = "red",
	[275160] = "orange",
	[277007] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("G'huun", {
	[-18109] = "long",
	[263235] = "alert",
	[263307] = "alarm",
	[263321] = "alarm",
	[263482] = "long",
	[267409] = "alert",
	[267412] = "alarm",
	[267427] = "alert",
	[267462] = "warning",
	[267509] = "info",
	[270287] = "alarm",
	[270373] = "alarm",
	[270447] = "alarm",
	[272506] = "alarm",
	[274582] = "alarm",
	[275160] = "warning",
	[277007] = {"info","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Uldir Trash", {
	[276540] = "red",
	[277047] = {"blue","yellow"},
	[278990] = "red",
})

BigWigs:AddSounds("Uldir Trash", {
	[276540] = "long",
	[277047] = "warning",
	[278990] = "long",
})
